### ISSUE TITLE
fileSize is bigger than actual

### ISSUE THREAD

**Issue by birdgg** [react-native-community/react-native-image-picker#514]
I have a image which size is 1.5mb, but the fileSize from response is much bigger

![screen shot 2017-03-16 at 15 45 35](https://cloud.githubusercontent.com/assets/4584859/23986819/1cfaa850-0a61-11e7-9619-34e5717e56be.png)
![img_0300](https://cloud.githubusercontent.com/assets/4584859/23986837/3289a8a6-0a61-11e7-8289-92e22dbb2b7a.PNG)

**Comment by irsyadmhdilham** [comment]
+1

**Comment by cloudslade** [comment]
Any progress on this issue @birdgg ?

**Comment by dylanslade** [comment]
I am experiencing this as well.

**Comment by AlexanderIgnacz** [comment]
Fixed by set ```imageFileType: 'png'``` at options

**Comment by vbro1293** [comment]
This still appears to be an issue on iOS, my original file is 1.6mb and the response fileSize is stating it as 4.3mb (without editing any quality/height/width params).

**Comment by Achilles718611** [comment]
This error is still appeared on 3.x.
I'm not sure why this issue is closed.

**Comment by codal-mpawar** [comment]
I am still facing this issue

**Comment by 4RGUS** [comment]
I am also facing this issue. Currently on version 4.7.0 
I tested this only on Android.
